#!/usr/bin/env perl

use FindBin;
use Test::More;
use Test::Exception;
use File::Compare;
use File::Temp qw(tempdir);

use FindBin;
use lib $FindBin::Bin.'/../lib';
use Reporter;

my $script_dir = $FindBin::Bin;

my $old_env = $ENV{'PERL5LIB'};
$ENV{'PERL5LIB'} = "$script_dir/../lib:$script_dir/../cpanlib/lib/perl5:";
$ENV{'PERL5LIB'} .= $old_env if (defined $old_env);

my $mapping_dir = "$script_dir/mapping";
my $mapping_bin = "$script_dir/../verify_mapping_quality.pl";
my ($command);

#==============================================================================
#UNIT TESTS

#1 => verify that the script saves output in the proper file locations
my $create_dir = tempdir(TEMPLATE => 'XXXXX', CLEANUP => 1) or die "Unable to create temporary file directory.";
my $reporter = Reporter->new;
my $results = $reporter->record_read_mapping('mapping/input/sample1.bam', 'mapping/input/sample2.bam', 'mapping/input/sample3.bam');
ok($results, "The method produces output.");
ok($results =~ tr/\n// == 8, "The correct output is generated by record_read_mapping.");

#2 => 


done_testing();
